// Generate a student-facing AI-use & supervision disclosure from a report.

import type { SupervisionReport } from "@agentsafe/core";
import { RUBRIC_LABELS, SSM, SSM_ORDER } from "@agentsafe/core";

export function disclosureMarkdown(report: SupervisionReport): string {
  const out: string[] = [];
  out.push(`# AI-Use & Supervision Disclosure`);
  out.push("");
  out.push(
    `_Repository:_ \`${report.repoId}\` — ${report.totalCommits} commits, ` +
      `${report.implFileCount} implementation / ${report.testFileCount} test files` +
      `${report.hasCi ? ", CI configured" : ""}.`,
  );
  out.push("");
  out.push(`## Supervision summary (Supervision Skill Model)`);
  out.push("");
  out.push(`| Area | Level | Evidence |`);
  out.push(`|---|---|---|`);
  for (const a of SSM_ORDER) {
    const r = report.areas[a];
    const level = r.score < 0 ? "_not assessed_" : `${RUBRIC_LABELS[r.score]} (${r.score}/3)`;
    out.push(`| **${a} ${SSM[a].name}** | ${level} | ${r.reasoning.replace(/\|/g, "/")} |`);
  }
  out.push("");
  out.push(
    `_Overall (assessed areas): ${report.overall}/3 — ${report.overallLabel}. ` +
      `S3 (Verify) and S6 (Orchestrate) are computed from git history; S1/S2/S4/S5 require an instructor LLM pass._`,
  );
  out.push("");

  if (report.aiUsage) {
    const ai = report.aiUsage;
    out.push(`## AI-tool usage (detected)`);
    out.push("");
    out.push(
      `Evidence level: **${ai.level}** (${Math.round(ai.weightedPct * 100)}% of the weighted signal). ` +
        `Explicit signals: ${ai.explicitSignals.length ? ai.explicitSignals.join(", ") : "none"}. ` +
        `Top behavioral signals: ${ai.topBehavioral.length ? ai.topBehavioral.join(", ") : "none"}.`,
    );
    out.push("");
  }

  out.push(`## Your statement (please complete)`);
  out.push("");
  out.push(`- **Which AI tools did you use, and for what parts of the work?**`);
  out.push(`- **What did you accept, modify, or reject** from the agent's output?`);
  out.push(`- **Can you explain and defend every line you submitted?** Note anything you cannot.`);
  out.push("");
  out.push(`---`);
  out.push(`_Generated by Agentic-SE Coach. Detected signals are evidence to discuss, not a grade._`);
  return out.join("\n");
}
